[package]
name = "missingno-sg1000"
version.workspace = true
edition = "2024"

[dependencies]
missingno-core = { path = "../../missingno/core" }
missingno-ti-psg = { path = "../../chips/ti-psg" }
missingno-ti-vdp = { path = "../../chips/ti-vdp" }
missingno-zilog-z80 = { path = "../../chips/zilog-z80" }
rgb = { workspace = true }
sha2 = { version = "0.11" }
