[package]
name = "missingno-sg1000"
version.workspace = true
edition = "2024"

[dependencies]
missingno-core = { path = "../../missingno/core" }
missingno-ti-psg = { path = "../../chips/ti-psg", features = ["inspect"] }
missingno-ti-vdp = { path = "../../chips/ti-vdp" }
missingno-zilog-z80 = { path = "../../chips/zilog-z80" }
rgb = { workspace = true }
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
ron = "0.12"
missingno-test-support = { path = "../../missingno/test-support" }
