[package]
name = "missingno-curator"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.4", features = ["derive"] }
iced = { version = "0.14.0", features = ["smol", "image", "wgpu"] }
gilrs = "0.11"
jiff = "0.2"
missingno-core = { path = "../missingno-core" }
missingno-iced = { path = "../missingno-iced" }
missingno-gamedb = { path = "../../missingno-gamedb/crates/gamedb" }
missingno-session = { path = "../missingno-session", features = ["tools", "audio-output"] }
missingno-vcs = { path = "../missingno-vcs" }
serde_json = "1"
sha1 = "0.11"
smol = "2"
ureq = "3"

[dev-dependencies]
tempfile = "3"
