[package]
name = "missingno-mos-6502"
version.workspace = true
edition = "2024"

[dependencies]
missingno-core = { path = "../../missingno/core" }

[dev-dependencies]
missingno-test-support = { path = "../../missingno/test-support" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
