[package]
name = "missingno-nes"
version = "0.1.0"
edition = "2024"

[features]
morepork = ["dep:morepork", "dep:sha2"]

[dependencies]
missingno-6502 = { path = "../missingno-6502" }
morepork = { git = "https://github.com/ajoneil/morepork", optional = true }
sha2 = { version = "0.11", optional = true }

[dev-dependencies]
