[package]
name = "missingno-gbc"
version.workspace = true
authors = ["Andrew O'Neil <andy@andyofniall.net>"]
edition = "2024"
license = "MIT"

[features]
morepork = ["missingno-gb/morepork"]

[dependencies]
missingno-gb = { path = "../gb" }
missingno-core = { path = "../../missingno/core" }
rgb = { workspace = true }

[dev-dependencies]
missingno-gb = { path = "../gb", features = ["test-support"] }
missingno-test-support = { path = "../../missingno/test-support" }
